"""
run_and_log.py — TaintP2X Post-Run Logger
==========================================
Run this AFTER python3 run_download_and_check.py finishes.

RECOMMENDED workflow (captures full scan output too):
    1. python3 run_download_and_check.py 2>&1 | tee NewOutputs/.last_scan_log.txt
    2. python3 run_and_log.py

OR simple workflow (findings only, no scan log):
    1. python3 run_download_and_check.py
    2. python3 run_and_log.py
"""

import json
import os
import sys
from datetime import datetime, timezone

# ─── Config ────────────────────────────────────────────────────────────────────────────────
OUTPUT_DIR    = "./NewOutputs"
MASTER_FILE   = os.path.join(OUTPUT_DIR, "all_outputs.md")
INDEX_FILE    = os.path.join(OUTPUT_DIR, ".run_index.json")
SCAN_LOG      = os.path.join(OUTPUT_DIR, ".last_scan_log.txt")  # written by tee
SOURCES_FILE  = "test_source.json"
PYSA_RESULTS  = "./pysa_result"
DIVIDER       = "═" * 72
THIN_DIVIDER  = "─" * 72
# ────────────────────────────────────────────────────────────────────────────────


def read_test_sources():
    with open(SOURCES_FILE, "r") as f:
        return json.load(f)


def load_index():
    if not os.path.exists(INDEX_FILE):
        return []
    with open(INDEX_FILE, "r") as f:
        return json.load(f)


def save_index(idx):
    with open(INDEX_FILE, "w") as f:
        json.dump(idx, f, indent=2)


def read_scan_log():
    """Read the scan log written by tee, if it exists. Returns text or None."""
    if not os.path.exists(SCAN_LOG):
        return None
    with open(SCAN_LOG, "r", errors="replace") as f:
        content = f.read().strip()
    return content if content else None


def find_pysa_output(name_with_owner):
    safe_name = name_with_owner.replace("/", "__")
    path = os.path.join(PYSA_RESULTS, f"pysa-runs_{safe_name}", "taint-output.json")
    return path if os.path.exists(path) else None


def get_all_pysa_findings(taint_output_path):
    callables = set()
    with open(taint_output_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                if obj.get("kind") == "issue":
                    c = obj.get("data", {}).get("callable", "")
                    if c:
                        callables.add(c)
            except json.JSONDecodeError:
                continue
    return sorted(callables)


def print_and_capture_findings(callables):
    """Print all findings to terminal and return as text."""
    print(f"\n{DIVIDER}")
    print(f"  ALL PYSA FINDINGS  ({len(callables)} unique callables flagged)")
    print(f"{DIVIDER}\n")
    lines = []
    for i, c in enumerate(callables, 1):
        line = f"  {i:4}. {c}"
        print(line)
        lines.append(line)
    print(f"\n{DIVIDER}\n")
    return "\n".join(lines)


def extract_package_name(name_with_owner):
    return name_with_owner.split("/")[-1].lower()


def build_toc(index):
    lines = [
        "# TaintP2X — All Run Outputs\n",
        "> Auto-generated by `run_and_log.py`.\n",
        "> Run `python3 run_and_log.py` after each `python3 run_download_and_check.py` to log results.\n",
        "",
        "## Quick Reference Index\n",
        "| Run | Timestamp | Repository | Commit | Callables Found | Individual File |",
        "|-----|-----------|------------|--------|-----------------|-----------------|",
    ]
    for e in index:
        lines.append(
            f"| [Run #{e['run_num']}](#run-{e['run_num']}) "
            f"| {e['timestamp'][:16]} "
            f"| `{e['repo']}` "
            f"| `{e['commit_hash'][:8]}...` "
            f"| {e.get('callables_found','?')} "
            f"| [{e['individual_file']}](./{e['individual_file']}) |"
        )
    lines.append("")
    return "\n".join(lines)


def build_run_block(run_num, source, timestamp_str, findings_text, individual_file, taint_path, scan_log):
    repo        = source.get("nameWithOwner", "unknown")
    commit_hash = source.get("commit_hash", "unknown")
    url         = source.get("url", "unknown")
    package     = extract_package_name(repo)

    scan_log_section = ""
    if scan_log:
        scan_log_section = f"""{THIN_DIVIDER}
### Full Scan Terminal Output

```
{scan_log}
```
"""

    return f"""
{DIVIDER}
## Run #{run_num} — {repo} @ `{commit_hash[:12]}...`
{DIVIDER}

| Field | Value |
|---|---|
| **Run Number** | #{run_num} |
| **Timestamp** | {timestamp_str} |
| **Repository** | `{repo}` |
| **URL** | {url} |
| **Commit Hash** | `{commit_hash}` |
| **PyPI Package** | `{package}` |
| **Taint Output File** | `{taint_path}` |
| **Scan Log Captured** | {'Yes' if scan_log else 'No (run with tee to capture)'} |
| **Individual File** | [{individual_file}](./{individual_file}) |

{scan_log_section}
{THIN_DIVIDER}
### All Pysa Findings (Complete Callable List)

```
{findings_text.strip() if findings_text else "No findings found in taint-output.json."}
```

"""


def rebuild_master_file(index, new_run_block):
    toc = build_toc(index)
    all_blocks = []
    for e in index[:-1]:
        fpath = os.path.join(OUTPUT_DIR, e["individual_file"])
        if os.path.exists(fpath):
            content = open(fpath).read()
            marker = f"## Run #{e['run_num']}"
            idx = content.find(marker)
            if idx != -1:
                all_blocks.append(content[idx:])
    all_blocks.append(new_run_block)
    with open(MASTER_FILE, "w") as f:
        f.write(toc)
        f.write("\n---\n")
        for block in all_blocks:
            f.write(block)


def save_individual_file(run_num, source, timestamp_str, run_block, individual_file):
    repo        = source.get("nameWithOwner", "unknown")
    commit_hash = source.get("commit_hash", "unknown")
    header = (
        f"# Run #{run_num} — {repo}\n\n"
        f"> Commit: `{commit_hash}`  \n"
        f"> Timestamp: {timestamp_str}  \n"
        f"> Part of master log: [all_outputs.md](./all_outputs.md)\n\n"
    )
    fpath = os.path.join(OUTPUT_DIR, individual_file)
    with open(fpath, "w") as f:
        f.write(header)
        f.write(run_block)


def main():
    if not os.path.exists(SOURCES_FILE):
        print(f"[ERROR] {SOURCES_FILE} not found. Run from the TaintP2X directory.")
        sys.exit(1)

    sources = read_test_sources()
    if not sources:
        print(f"[ERROR] {SOURCES_FILE} is empty.")
        sys.exit(1)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    index         = load_index()
    run_num       = len(index) + 1
    source        = sources[0]
    repo          = source.get("nameWithOwner", "unknown")
    commit_hash   = source.get("commit_hash", "unknown")
    package       = extract_package_name(repo)
    timestamp_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    safe_repo       = repo.replace("/", "_")
    short_commit    = commit_hash[:8]
    individual_file = f"run_{run_num:03d}_{safe_repo}_{short_commit}.md"

    print(f"\n{DIVIDER}")
    print(f"  TaintP2X Output Logger — Run #{run_num}")
    print(f"  Repo:   {repo}")
    print(f"  Commit: {commit_hash}")
    print(f"  Time:   {timestamp_str}")
    print(f"{DIVIDER}\n")

    # Find the taint output from the last scan
    taint_path = find_pysa_output(repo)

    if not taint_path:
        print(f"[ERROR] taint-output.json not found for '{repo}'.")
        print(f"        Make sure you ran python3 run_download_and_check.py first.")
        sys.exit(1)

    print(f"[logger] Reading: {taint_path}\n")

    # Read scan log if available (written by tee)
    scan_log = read_scan_log()
    if scan_log:
        print(f"[logger] Scan log found ({len(scan_log)} chars) — will be included in output.")
    else:
        print(f"[logger] No scan log found. Tip: run the scan with:")
        print(f"         python3 run_download_and_check.py 2>&1 | tee NewOutputs/.last_scan_log.txt")
        print()

    # Get and print all findings
    callables     = get_all_pysa_findings(taint_path)
    findings_text = print_and_capture_findings(callables)

    # Build and save run block
    run_block = build_run_block(
        run_num, source, timestamp_str, findings_text, individual_file, taint_path, scan_log
    )

    save_individual_file(run_num, source, timestamp_str, run_block, individual_file)

    # Clear the scan log after consuming it so it doesn't show up in the next run
    if scan_log and os.path.exists(SCAN_LOG):
        os.remove(SCAN_LOG)

    index.append({
        "run_num":         run_num,
        "timestamp":       timestamp_str,
        "repo":            repo,
        "commit_hash":     commit_hash,
        "package":         package,
        "callables_found": len(callables),
        "individual_file": individual_file,
    })
    save_index(index)
    rebuild_master_file(index, run_block)

    print(f"{DIVIDER}")
    print(f"  SAVED — Run #{run_num}")
    print(f"  Individual: NewOutputs/{individual_file}")
    print(f"  Master:     NewOutputs/all_outputs.md")
    print(f"{DIVIDER}\n")


if __name__ == "__main__":
    main()
